language: rust
rust:
  - stable
  - beta
  - nightly
branches:
  only:
    - master
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
script:
  - cargo build --verbose
  - cargo test --verbose